my own mods

diff --git a/buildroot/share/git/mfpr b/buildroot/share/git/mfpr
--- a/buildroot/share/git/mfpr
+++ b/buildroot/share/git/mfpr
@@ -1,39 +1,40 @@
 #!/usr/bin/env bash
 #
-# mfpr [1|2|3]
+# mfpr
 #
-# Make a PR against bugfix-1.1.x or bugfix-2.0.x
+# Make a PR of the current branch against RCBugFix or dev
 #
 
-[[ $# < 2 && $1 != "-h" && $1 != "--help" ]] || { echo "usage: `basename $0` [1|2|3] [branch]" 1>&2 ; exit 1; }
+MFINFO=$(mfinfo "$@") || exit
 
-MFINFO=$(mfinfo "$@") || exit 1
 IFS=' ' read -a INFO <<< "$MFINFO"
+
 ORG=${INFO[0]}
 FORK=${INFO[1]}
 REPO=${INFO[2]}
 TARG=${INFO[3]}
 BRANCH=${INFO[4]}
-OLDBRANCH=${INFO[5]}
 
-[[ $BRANCH == $TARG ]] && { echo "Can't create a PR from the PR Target ($BRANCH). Make a copy first." 1>&2 ; exit 1; }
+if [[ $BRANCH == "(no" ]]; then
+  echo "Git is busy with merge, rebase, etc."
+  exit 1
+fi
 
-[[ $BRANCH != $OLDBRANCH ]] && { git checkout $BRANCH || exit 1; }
+if [[ ! -z "$1" ]]; then { BRANCH=$1 ; git checkout $1 || exit 1; } fi
 
-# See if it's been pushed yet
+if [[ $BRANCH == $TARG ]]; then
+  echo "Can't make a PR from $BRANCH" ; exit
+fi
+
 if [ -z "$(git branch -vv | grep ^\* | grep \\[origin)" ]; then firstpush; fi
 
-which xdg-open >/dev/null && TOOL=xdg-open
-which gnome-open >/dev/null && TOOL=gnome-open
-which open >/dev/null && TOOL=open
+TOOL=$(which gnome-open xdg-open open | awk '{ print $1 }')
 URL="https://github.com/$ORG/$REPO/compare/$TARG...$FORK:$BRANCH?expand=1"
 
-if [ -z "$OPEN" ]; then
+if [ -z "$TOOL" ]; then
   echo "Can't find a tool to open the URL:"
   echo $URL
 else
   echo "Opening a New PR Form..."
-  "$OPEN" "$URL"
+  "$TOOL" "$URL"
 fi
-
-[[ $BRANCH != $OLDBRANCH ]] && git checkout $OLDBRANCH
